# This workflow will automatically compile paper.md to a pdf upon push or pull request.
# For more information see: https://github.com/marketplace/actions/open-journals-pdf-generator

name: paper_compilation

on: [push, pull_request]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: paper.pdf
